### ISSUE TITLE
Figure out a light-weight, easily managed DNS service that can run on docker container

### ISSUE THREAD

**Issue by htpvu** [jhu-sheridan-libraries/jhuda-operations#2]
Look int to dnsmasq

context for this ticket can be found here: https://docs.google.com/document/d/1ynNYuiukEzc-rH-JoIDwXTF02jeYTu_gmZcXRcKHOsA/edit?pli=1

**Comment by derekbelrose** [comment]
DNSmasq is not required.  We will be using CoreDNS (comes by default with Kubernetes clusters)
